env:
    node: true

extends:
    - 'airbnb-base'

parserOptions:
    ecmaVersion: 10

rules:
    no-console: 0
    import/extensions: 0 # FIXME: remove when rule will be adjusted for new nodejs version
