name: CI

on:
  push:
    branches: [ master ]
#  pull_request:               // add when it's needed
#    branches: [ master ]      // add when it's needed

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
    - uses: actions/setup-node@v1
    - with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        make install
    - name: run linter + fix
      run: |
        make lint
